Ejercicios de Arrays y Matrices con NumPy


Ejercicio 1: Crear un array de 10 elementos con ceros.

In [2]:
import numpy as np
array_ceros = np.zeros(10)

print(array_ceros)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ejercicio 2: Genera un array con los números del 1 al 20.

In [3]:
import numpy as np
array=np.arange(1,21)

print(array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Ejercicio 3: Crea un array con los números pares del 2 al 50.

In [4]:
import numpy as np
array_pares = np.arange(2, 51, 2)

print(array_pares)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.

In [5]:
import numpy as np
np.random.seed(42)
matriz_aleatoria = np.random.rand(4, 4)

print(matriz_aleatoria)


[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]


Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
import numpy as np
suma = a + b

print(suma)


[5 7 9]


Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

In [7]:
import numpy as np
matriz1 = np.random.randint(1, 11, (3, 3))
matriz2 = np.random.randint(1, 11, (3, 3))

resultado = np.dot(matriz1, matriz2)

print("Matriz 1:")
print(matriz1)
print("\nMatriz 2:")
print(matriz2)
print("\nResultado de la multiplicación:")
print(resultado)


Matriz 1:
[[10  6  9]
 [ 1 10  3]
 [ 7  4  9]]

Matriz 2:
[[3 5 3]
 [7 5 9]
 [7 2 4]]

Resultado de la multiplicación:
[[135  98 120]
 [ 94  61 105]
 [112  73  93]]


Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

In [8]:
import numpy as np
array_random = np.random.randint(1, 101, 15)

maximo = np.max(array_random)
minimo = np.min(array_random)
promedio = np.mean(array_random)

print("Array generado:", array_random)
print("Máximo:", maximo)
print("Mínimo:", minimo)
print("Promedio:", promedio)


Array generado: [89 60 14  9 90 53  2 84 92 60 71 44  8 47 35]
Máximo: 92
Mínimo: 2
Promedio: 50.53333333333333


Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

In [9]:
import numpy as np
matriz = np.arange(1, 26).reshape(5, 5)

diagonal = np.diagonal(matriz)

print("Matriz 5x5:")
print(matriz)
print("\nDiagonal de la matriz:")
print(diagonal)


Matriz 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal de la matriz:
[ 1  7 13 19 25]


Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna

In [10]:
import numpy as np
matriz = np.random.randint(1, 21, (5, 5))

suma_filas = np.sum(matriz, axis=1)
suma_columnas = np.sum(matriz, axis=0)

print("Matriz 5x5:")
print(matriz)
print("\nSuma de cada fila:")
print(suma_filas)
print("\nSuma de cada columna:")
print(suma_columnas)



Matriz 5x5:
[[14 17  4 18  8]
 [ 4  2  6 10  4]
 [18 12  2 10  4]
 [14 16 15  8 14]
 [ 8 16 13 18 15]]

Suma de cada fila:
[61 26 46 67 70]

Suma de cada columna:
[58 63 40 64 45]
